// i18n text tables kept separate for reuse across micro-sites.
// Loaded via <script src="js/text.js"></script> before main.js.
(function () {
  const BUTTON_TEXT = {
    en: {
      initial: "Receive",
      after: [
        "Receive Another",
        "Seek More Power",
        "Ask Again",
        "Request Another Gift",
        "Challenge Fate",
        "Embrace Another Burden",
        "The Entity Waits",
        "Take Another",
      ],
    },
    ko: {
      initial: "받기",
      after: [
        "더 받기",
        "다시 요청",
        "또 다른 선물",
        "운명에 도전",
        "또 다른 짐을 짊어지세요",
        "신성한 존재가 기다립니다",
        "계속하세요",
      ],
    },
    ja: {
      initial: "受け取る",
      after: [
        "もう一度",
        "さらに力を",
        "再び問う",
        "別の贈り物を",
        "運命に挑む",
        "新たな重荷を",
        "神は待っている",
        "受け取り続ける",
      ],
    },
    zh: {
      initial: "接受",
      after: [
        "再接受一次",
        "寻求更多力量",
        "再次请求",
        "接受另一个恩赐",
        "挑战命运",
        "拥抱新的负担",
        "神在等待",
        "继续接受",
      ],
    },
  };

  const UI_TEXT = {
    en: {
      langLabel: "Language",
      close: "Close",
      title: "Stateful Paradox System",
      desc: "An experimental system observing long-term interaction with paradox-generating entities.",
      btn: "Generate",
      loading: "System processing...",
      copy: "Copy",
      copied: "Copied",
      copyError: "Copy failed",
      save: "Archive Observation",
      saveSuccess: "Observation archived",
      saveDuplicate: "Already archived",
      generated: "Observations",
      divineFavor: "Interaction Depth",
      achievements: "Milestones",
      treasury: "Observation Log",
      support: "Support",
      privacy: "Privacy",
      about: "About",
      contact: "Contact",
      privacyTitle: "Privacy Policy",
      achievementsTitle: "System Milestones",
      treasuryTitle: "Observation Log",
      exportCollection: "Export Observations",
      clearAll: "Clear All",
      legendaryGift: "★ LEGENDARY PATTERN ★",
      treasuryEmptyTitle: "No observations recorded.",
      treasuryEmptyDesc: "Archive patterns to build your observation log.",
      removedFromTreasury: "Removed from log",
      treasuryIsEmpty: "Log is empty",
      exportedCollection: "Observations exported to clipboard",
      exportFailed: "Export failed",
      clearConfirm: "Clear entire observation log? This cannot be undone.",
      treasuryCleared: "Log cleared",
      footerNote: "© 2025 The Divine Paradox | Experimental System",
      emptyResult: "System output will appear here",
      error: "System unavailable. Examine again.",
      rarityLabels: { common: "common", rare: "rare", epic: "epic", legendary: "legendary" },
      // About Modal
      aboutTitle: "About This System",
      aboutWhatIs: "What This Is",
      aboutWhatIsP1: "This is an <strong>experimental system</strong> designed to observe behavior-level constraints and internal state transitions in a paradox-generating entity.",
      aboutWhatIsP2: "The purpose is <strong>behavior observation</strong>, not providing instant utility or entertainment.",
      aboutWhatNot: "What This Is NOT",
      aboutNotProductivity: "A productivity tool",
      aboutNotChatbot: "A chatbot demo",
      aboutNotUtility: "An instant utility provider",
      aboutDesign: "System Design",
      aboutDesignIntro: "This system implements:",
      aboutStateful: "<strong>Stateful behavior</strong> — The entity maintains internal state across interactions",
      aboutLongTerm: "<strong>Long-term interaction</strong> — Patterns emerge over time, not in single encounters",
      aboutBounded: "<strong>Bounded memory</strong> — Recent preferences influence future responses",
      aboutBehavior: "<strong>Behavior-driven constraints</strong> — Response policies prevent shallow loops",
      aboutHowTo: "How to Observe",
      aboutHowToText: "Short interactions will not reveal its design. Time and context accumulation are required.",
      aboutTechnical: "Technical Details",
      aboutTechnicalText: "Static frontend + serverless function. Source available at",
      aboutGithub: "GitHub",
    },
    ko: {
      langLabel: "언어",
      close: "닫기",
      title: "상태 기반 패러독스 시스템",
      desc: "패러독스 생성 엔티티와의 장기 상호작용을 관찰하는 실험적 시스템입니다.",
      btn: "생성",
      loading: "시스템 처리 중...",
      copy: "복사",
      copied: "복사됨",
      copyError: "복사 실패",
      save: "관찰 기록 보관",
      saveSuccess: "관찰 기록됨",
      saveDuplicate: "이미 보관됨",
      generated: "관찰 횟수",
      divineFavor: "상호작용 깊이",
      achievements: "마일스톤",
      treasury: "관찰 로그",
      support: "후원하기",
      privacy: "개인정보",
      about: "소개",
      contact: "문의",
      privacyTitle: "개인정보 처리방침",
      achievementsTitle: "시스템 마일스톤",
      treasuryTitle: "관찰 로그",
      exportCollection: "관찰 내보내기",
      clearAll: "전체 삭제",
      legendaryGift: "★ 전설적 패턴 ★",
      treasuryEmptyTitle: "관찰 기록이 없습니다.",
      treasuryEmptyDesc: "패턴을 보관하여 관찰 로그를 구축하세요.",
      removedFromTreasury: "로그에서 제거됨",
      treasuryIsEmpty: "로그가 비어 있습니다",
      exportedCollection: "관찰 로그를 클립보드로 내보냈습니다",
      exportFailed: "내보내기 실패",
      clearConfirm: "전체 관찰 로그를 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.",
      treasuryCleared: "로그 삭제됨",
      footerNote: "© 2025 The Divine Paradox | 실험적 시스템",
      emptyResult: "시스템 출력이 여기에 나타납니다",
      error: "시스템 사용 불가. 다시 검토하세요.",
      rarityLabels: { common: "일반", rare: "희귀", epic: "영웅", legendary: "전설" },
      // About Modal
      aboutTitle: "이 시스템에 대하여",
      aboutWhatIs: "이것은 무엇인가",
      aboutWhatIsP1: "이것은 패러독스 생성 엔티티의 <strong>행동 수준 제약 조건</strong>과 <strong>내부 상태 전이</strong>를 관찰하기 위해 설계된 <strong>실험적 시스템</strong>입니다.",
      aboutWhatIsP2: "목적은 즉각적인 유틸리티나 엔터테인먼트를 제공하는 것이 아니라 <strong>행동 관찰</strong>입니다.",
      aboutWhatNot: "이것이 무엇이 아닌가",
      aboutNotProductivity: "생산성 도구",
      aboutNotChatbot: "챗봇 데모",
      aboutNotUtility: "즉각적인 유틸리티 제공자",
      aboutDesign: "시스템 설계",
      aboutDesignIntro: "이 시스템은 다음을 구현합니다:",
      aboutStateful: "<strong>상태 기반 행동</strong> — 엔티티는 상호작용 간 내부 상태를 유지합니다",
      aboutLongTerm: "<strong>장기 상호작용</strong> — 패턴은 단일 만남이 아니라 시간이 지남에 따라 나타납니다",
      aboutBounded: "<strong>제한된 메모리</strong> — 최근 선호도가 미래 응답에 영향을 미칩니다",
      aboutBehavior: "<strong>행동 기반 제약 조건</strong> — 응답 정책이 얕은 루프를 방지합니다",
      aboutHowTo: "관찰 방법",
      aboutHowToText: "짧은 상호작용으로는 설계가 드러나지 않습니다. 시간과 맥락의 누적이 필요합니다.",
      aboutTechnical: "기술적 세부사항",
      aboutTechnicalText: "정적 프런트엔드 + 서버리스 함수. 소스는 다음에서 확인 가능:",
      aboutGithub: "GitHub",
    },
    ja: {
      langLabel: "言語",
      close: "閉じる",
      title: "ステートフル・パラドックス・システム",
      desc: "パラドックス生成エンティティとの長期的相互作用を観察する実験的システム。",
      btn: "生成",
      loading: "システム処理中...",
      copy: "コピー",
      copied: "コピーしました",
      copyError: "コピー失敗",
      save: "観察記録を保存",
      saveSuccess: "観察記録されました",
      saveDuplicate: "既に保存済み",
      generated: "観測数",
      divineFavor: "相互作用の深さ",
      achievements: "マイルストーン",
      treasury: "観察ログ",
      support: "支援する",
      privacy: "プライバシー",
      about: "概要",
      contact: "連絡先",
      privacyTitle: "プライバシーポリシー",
      achievementsTitle: "システムマイルストーン",
      treasuryTitle: "観察ログ",
      exportCollection: "観察データをエクスポート",
      clearAll: "すべて削除",
      legendaryGift: "★ 伝説的パターン ★",
      treasuryEmptyTitle: "観察記録がありません。",
      treasuryEmptyDesc: "パターンを保存して観察ログを構築してください。",
      removedFromTreasury: "ログから削除されました",
      treasuryIsEmpty: "ログは空です",
      exportedCollection: "観察データをクリップボードにエクスポートしました",
      exportFailed: "エクスポート失敗",
      clearConfirm: "観察ログをすべて削除しますか？この操作は元に戻せません。",
      treasuryCleared: "ログを削除しました",
      footerNote: "© 2025 The Divine Paradox | 実験的システム",
      emptyResult: "システム出力がここに表示されます",
      error: "システム利用不可。再検証してください。",
      rarityLabels: { common: "コモン", rare: "レア", epic: "エピック", legendary: "レジェンダリー" },
      // About Modal
      aboutTitle: "このシステムについて",
      aboutWhatIs: "これは何か",
      aboutWhatIsP1: "これはパラドックス生成エンティティの<strong>行動レベル制約</strong>と<strong>内部状態遷移</strong>を観察するために設計された<strong>実験的システム</strong>です。",
      aboutWhatIsP2: "目的は即時的なユーティリティやエンターテインメントを提供することではなく、<strong>行動観察</strong>です。",
      aboutWhatNot: "これは何ではないか",
      aboutNotProductivity: "生産性ツール",
      aboutNotChatbot: "チャットボットのデモ",
      aboutNotUtility: "即時的なユーティリティ提供者",
      aboutDesign: "システム設計",
      aboutDesignIntro: "このシステムは以下を実装しています:",
      aboutStateful: "<strong>ステートフルな振る舞い</strong> — エンティティは相互作用間で内部状態を維持します",
      aboutLongTerm: "<strong>長期的相互作用</strong> — パターンは単一の出会いではなく時間の経過とともに現れます",
      aboutBounded: "<strong>制限されたメモリ</strong> — 最近の好みが将来の応答に影響します",
      aboutBehavior: "<strong>行動駆動型制約</strong> — 応答ポリシーが浅いループを防ぎます",
      aboutHowTo: "観察方法",
      aboutHowToText: "短い相互作用では設計は明らかになりません。時間と文脈の蓄積が必要です。",
      aboutTechnical: "技術的詳細",
      aboutTechnicalText: "静的フロントエンド + サーバーレス関数。ソースはこちら:",
      aboutGithub: "GitHub",
    },
    zh: {
      langLabel: "语言",
      close: "关闭",
      title: "有状态悖论系统",
      desc: "观察与悖论生成实体长期交互的实验系统。",
      btn: "生成",
      loading: "系统处理中...",
      copy: "复制",
      copied: "已复制",
      copyError: "复制失败",
      save: "保存观察记录",
      saveSuccess: "观察记录已保存",
      saveDuplicate: "已保存",
      generated: "观察次数",
      divineFavor: "交互深度",
      achievements: "里程碑",
      treasury: "观察日志",
      support: "支持",
      privacy: "隐私",
      about: "关于",
      contact: "联系",
      privacyTitle: "隐私政策",
      achievementsTitle: "系统里程碑",
      treasuryTitle: "观察日志",
      exportCollection: "导出观察数据",
      clearAll: "全部清空",
      legendaryGift: "★ 传说模式 ★",
      treasuryEmptyTitle: "暂无观察记录。",
      treasuryEmptyDesc: "保存模式以建立观察日志。",
      removedFromTreasury: "已从日志移除",
      treasuryIsEmpty: "日志为空",
      exportedCollection: "观察数据已导出到剪贴板",
      exportFailed: "导出失败",
      clearConfirm: "确定要清空所有观察日志吗？此操作无法撤销。",
      treasuryCleared: "日志已清空",
      footerNote: "© 2025 The Divine Paradox | 实验系统",
      emptyResult: "系统输出将显示在此处",
      error: "系统不可用。请重新验证。",
      rarityLabels: { common: "普通", rare: "稀有", epic: "史诗", legendary: "传说" },
      // About Modal
      aboutTitle: "关于此系统",
      aboutWhatIs: "这是什么",
      aboutWhatIsP1: "这是一个用于观察悖论生成实体的<strong>行为级别约束</strong>和<strong>内部状态转换</strong>的<strong>实验系统</strong>。",
      aboutWhatIsP2: "目的是<strong>行为观察</strong>，而非提供即时效用或娱乐。",
      aboutWhatNot: "这不是什么",
      aboutNotProductivity: "生产力工具",
      aboutNotChatbot: "聊天机器人演示",
      aboutNotUtility: "即时效用提供者",
      aboutDesign: "系统设计",
      aboutDesignIntro: "此系统实现了:",
      aboutStateful: "<strong>有状态行为</strong> — 实体在交互间维护内部状态",
      aboutLongTerm: "<strong>长期交互</strong> — 模式随时间显现，而非单次相遇",
      aboutBounded: "<strong>有界记忆</strong> — 近期偏好影响未来响应",
      aboutBehavior: "<strong>行为驱动约束</strong> — 响应策略防止浅层循环",
      aboutHowTo: "观察方法",
      aboutHowToText: "短期交互不会揭示其设计。需要时间和语境的积累。",
      aboutTechnical: "技术详情",
      aboutTechnicalText: "静态前端 + 无服务器函数。源代码:",
      aboutGithub: "GitHub",
    },
  };

  function getRandomButtonText(lang) {
    const texts = BUTTON_TEXT[lang] || BUTTON_TEXT.en;
    const afterTexts = texts.after || texts.initial;
    return afterTexts[Math.floor(Math.random() * afterTexts.length)];
  }

  function getRarityLabel(rarityName, lang) {
    const t = UI_TEXT[lang] || UI_TEXT.en;
    return (t.rarityLabels && t.rarityLabels[rarityName]) ? t.rarityLabels[rarityName] : rarityName;
  }

  window.DP_TEXT = {
    BUTTON_TEXT,
    UI_TEXT,
    getRandomButtonText,
    getRarityLabel,
  };
})();

