// i18n text tables kept separate for reuse across micro-sites.
// Loaded via <script src="js/text.js"></script> before main.js.
(function () {
  const BUTTON_TEXT = {
    en: {
      initial: "Receive",
      after: [
        "Receive Another",
        "Seek More Power",
        "Ask Again",
        "Request Another Gift",
        "Challenge Fate",
        "Embrace Another Burden",
        "The Entity Waits",
        "Take Another",
      ],
    },
    ko: {
      initial: "받기",
      after: [
        "더 받기",
        "다시 요청",
        "또 다른 선물",
        "운명에 도전",
        "또 다른 짐을 짊어지세요",
        "신성한 존재가 기다립니다",
        "계속하세요",
      ],
    },
    ja: {
      initial: "受け取る",
      after: [
        "もう一度",
        "さらに力を",
        "再び問う",
        "別の贈り物を",
        "運命に挑む",
        "新たな重荷を",
        "神は待っている",
        "受け取り続ける",
      ],
    },
    zh: {
      initial: "接受",
      after: [
        "再接受一次",
        "寻求更多力量",
        "再次请求",
        "接受另一个恩赐",
        "挑战命运",
        "拥抱新的负担",
        "神在等待",
        "继续接受",
      ],
    },
  };

  const UI_TEXT = {
    en: {
      langLabel: "Language",
      close: "Close",
      title: "Receive Your Gift",
      desc: "The Divine Entity offers you power, but every blessing carries its burden.",
      btn: "Receive",
      loading: "The Divine Entity shifts...",
      copy: "Copy",
      copied: "Copied",
      copyError: "Copy failed",
      save: "Archive Relic",
      saveSuccess: "Relic archived",
      saveDuplicate: "Already archived",
      generated: "Gifts Received",
      divineFavor: "Divine Favor",
      achievements: "Achievements",
      treasury: "Treasury",
      support: "Support",
      privacy: "Privacy",
      about: "About",
      contact: "Contact",
      privacyTitle: "Privacy Policy",
      achievementsTitle: "Achievements",
      treasuryTitle: "Your Treasury",
      exportCollection: "Export Collection",
      clearAll: "Clear All",
      legendaryGift: "✨ LEGENDARY GIFT ✨",
      treasuryEmptyTitle: "Your treasury is empty.",
      treasuryEmptyDesc: "Save abilities to build your collection.",
      removedFromTreasury: "Removed from Treasury",
      treasuryIsEmpty: "Treasury is empty",
      exportedCollection: "Collection exported to clipboard",
      exportFailed: "Export failed",
      clearConfirm: "Are you sure you want to clear your entire treasury? This cannot be undone.",
      treasuryCleared: "Treasury cleared",
      footerNote: "© 2025 The Divine Paradox",
      emptyResult: "Your gift will appear here",
      error: "The Divine Entity is silent. Try again.",
      rarityLabels: { common: "common", rare: "rare", epic: "epic", legendary: "legendary" },
    },
    ko: {
      langLabel: "언어",
      close: "닫기",
      title: "당신의 선물을 받으세요",
      desc: "신성한 존재가 당신에게 힘을 제안하지만, 모든 축복에는 짐이 따릅니다.",
      btn: "받기",
      loading: "신성한 존재가 변화합니다...",
      copy: "복사",
      copied: "복사됨",
      copyError: "복사 실패",
      save: "성물 봉인",
      saveSuccess: "성물함에 봉인됨",
      saveDuplicate: "이미 봉인된 성물",
      generated: "받은 선물",
      divineFavor: "신의 총애",
      achievements: "업적",
      treasury: "보물고",
      support: "후원하기",
      privacy: "개인정보",
      about: "소개",
      contact: "문의",
      privacyTitle: "개인정보 처리방침",
      achievementsTitle: "업적",
      treasuryTitle: "당신의 보물고",
      exportCollection: "컬렉션 내보내기",
      clearAll: "전체 삭제",
      legendaryGift: "✨ 전설의 선물 ✨",
      treasuryEmptyTitle: "보물고가 비어 있습니다.",
      treasuryEmptyDesc: "능력을 저장해 컬렉션을 쌓아보세요.",
      removedFromTreasury: "보물고에서 제거됨",
      treasuryIsEmpty: "보물고가 비어 있습니다",
      exportedCollection: "컬렉션을 클립보드로 내보냈습니다",
      exportFailed: "내보내기 실패",
      clearConfirm: "보물고를 전부 비우시겠어요? 이 작업은 되돌릴 수 없습니다.",
      treasuryCleared: "보물고를 비웠습니다",
      footerNote: "© 2025 The Divine Paradox",
      emptyResult: "당신의 선물이 여기에 나타납니다",
      error: "신성한 존재가 침묵합니다. 다시 시도하세요.",
      rarityLabels: { common: "일반", rare: "희귀", epic: "영웅", legendary: "전설" },
    },
    ja: {
      langLabel: "言語",
      close: "閉じる",
      title: "贈り物を受け取る",
      desc: "神聖な存在が力を捧げるが、全ての祝福には重荷が伴う。",
      btn: "受け取る",
      loading: "神聖な存在が移り変わる...",
      copy: "コピー",
      copied: "コピーしました",
      copyError: "コピー失敗",
      save: "聖遺物として収蔵",
      saveSuccess: "宝物庫に収蔵しました",
      saveDuplicate: "すでに収蔵済みです",
      generated: "受け取った贈り物",
      divineFavor: "神の加護",
      achievements: "実績",
      treasury: "宝物庫",
      support: "支援する",
      privacy: "プライバシー",
      about: "概要",
      contact: "連絡先",
      privacyTitle: "プライバシーポリシー",
      achievementsTitle: "実績",
      treasuryTitle: "あなたの宝物庫",
      exportCollection: "コレクションを書き出す",
      clearAll: "すべて削除",
      legendaryGift: "✨ 伝説の贈り物 ✨",
      treasuryEmptyTitle: "宝物庫は空です。",
      treasuryEmptyDesc: "能力を保存してコレクションを作りましょう。",
      removedFromTreasury: "宝物庫から削除しました",
      treasuryIsEmpty: "宝物庫は空です",
      exportedCollection: "コレクションをクリップボードに書き出しました",
      exportFailed: "書き出しに失敗しました",
      clearConfirm: "宝物庫をすべて消去しますか？この操作は元に戻せません。",
      treasuryCleared: "宝物庫を消去しました",
      footerNote: "© 2025 The Divine Paradox",
      emptyResult: "あなたの贈り物がここに現れます",
      error: "神聖な存在が沈黙しています。もう一度試してください。",
      rarityLabels: { common: "コモン", rare: "レア", epic: "エピック", legendary: "レジェンダリー" },
    },
    zh: {
      langLabel: "语言",
      close: "关闭",
      title: "接受你的恩赐",
      desc: "神圣存在赐予你力量，但每个祝福都伴随着负担。",
      btn: "接受",
      loading: "神圣存在正在转变...",
      copy: "复制",
      copied: "已复制",
      copyError: "复制失败",
      save: "封存圣物",
      saveSuccess: "已封存入宝库",
      saveDuplicate: "宝库中已存在",
      generated: "已接收恩赐",
      divineFavor: "神之眷顾",
      achievements: "成就",
      treasury: "宝库",
      support: "支持",
      privacy: "隐私",
      about: "关于",
      contact: "联系",
      privacyTitle: "隐私政策",
      achievementsTitle: "成就",
      treasuryTitle: "你的宝库",
      exportCollection: "导出收藏",
      clearAll: "全部清空",
      legendaryGift: "✨ 传说恩赐 ✨",
      treasuryEmptyTitle: "宝库是空的。",
      treasuryEmptyDesc: "保存能力来建立你的收藏。",
      removedFromTreasury: "已从宝库移除",
      treasuryIsEmpty: "宝库为空",
      exportedCollection: "收藏已导出到剪贴板",
      exportFailed: "导出失败",
      clearConfirm: "确定要清空整个宝库吗？此操作无法撤销。",
      treasuryCleared: "宝库已清空",
      footerNote: "© 2025 The Divine Paradox",
      emptyResult: "你的恩赐将出现在这里",
      error: "神圣存在保持沉默。请再试一次。",
      rarityLabels: { common: "普通", rare: "稀有", epic: "史诗", legendary: "传说" },
    },
  };

  function getRandomButtonText(lang) {
    const texts = BUTTON_TEXT[lang] || BUTTON_TEXT.en;
    const afterTexts = texts.after || texts.initial;
    return afterTexts[Math.floor(Math.random() * afterTexts.length)];
  }

  function getRarityLabel(rarityName, lang) {
    const t = UI_TEXT[lang] || UI_TEXT.en;
    return (t.rarityLabels && t.rarityLabels[rarityName]) ? t.rarityLabels[rarityName] : rarityName;
  }

  window.DP_TEXT = {
    BUTTON_TEXT,
    UI_TEXT,
    getRandomButtonText,
    getRarityLabel,
  };
})();

